# Generated by Django 2.1.4 on 2021-01-08 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auth',
        ),
    ]
